### ISSUE TITLE
symbols quote

### ISSUE THREAD

**Issue by jharby1** [kevinrider/phpetrade#2]
every time I use the bottom quote search, it automatically reverts to google or "GOOG". I tried many symbols but its not changing. is it a sandbox issue or a code issue?

$config = new Config(true);
$mk_obj = new Market($config);
$market_quotes_para["symbols"]= "FB";
$mk_quotes = $mk_obj->MarketGetQuotes($market_quotes_para);
print_r($mk_quotes);

**Comment by kevinrider** [comment]
Its a sandbox issue.  Its been a long time since I used the sandbox, but I'm pretty sure GOOG was the default ticker it returned for any market query.
