### ISSUE TITLE
Invalid auth/bad request (got a 401, expected HTTP/1.1 20X or a redirect)

### ISSUE THREAD

**Issue by jharby1** [kevinrider/phpetrade#3]
I'm getting the following error when i submit a preview order. below is my code as well. let me know what i'm doing wrong. Authentication works and i'm able to get symbol information, account information & transaction. It's only when I start to preview orders and place orders. 

PHP Fatal error:  Uncaught OAuthException: Invalid auth/bad request (got a 401, expected HTTP/1.1 20X or a redirect) in ../etrade/src/OAuthHTTP.php:31
Stack trace:
#0 ../etrade/src/OAuthHTTP.php(31): OAuth->fetch('https://api.etr...', '<?xml version="...', 'POST', Array)
#1 ../etrade/src/EndPointTrait.php(14): phpetrade\OAuthHTTP->GetResponse()
#2 ../etrade/src/Order.php(37): phpetrade\Order->getResponse(Object(phpetrade\Config), 'https://api.etr...', 'POST', Array)
#3 ../etrade/examples/test.php(87): phpetrade\Order->PreviewOrder('HN1xdY...', Array)
#4 {main}
  thrown in ../etrade/src/OAuthHTTP.php on line 31

$ord_obj = new Order($config);

//Preview Order
//EQ
$client_order_id = 'test' . rand_order_id(); //Some unique random order id

$order_preview_para["PreviewOrderRequest"]["orderType"] = "EQ"; //EQ, OPTN, SPREADS, BUT_WRITES,BUTTERFLY,IRON_BUTTERFLY,CONDOR,IRON_CONDOR,MF,MMF
$order_preview_para["PreviewOrderRequest"]["clientOrderId"] = "$client_order_id";
$order_preview_para["PreviewOrderRequest"]["Order"]["allOrNone"] = "false";
$order_preview_para["PreviewOrderRequest"]["Order"]["priceType"] = "LIMIT";
$order_preview_para["PreviewOrderRequest"]["Order"]["orderTerm"] = "GOOD_FOR_DAY";
$order_preview_para["PreviewOrderRequest"]["Order"]["marketSession"] = "REGULAR";
$order_preview_para["PreviewOrderRequest"]["Order"]["limitPrice"] = $ask-0.01;
$order_preview_para["PreviewOrderRequest"]["Order"]["Instrument"]["Product"]["securityType"] = "EQ";
$order_preview_para["PreviewOrderRequest"]["Order"]["Instrument"]["Product"]["symbol"] = "SLVO";
$order_preview_para["PreviewOrderRequest"]["Order"]["Instrument"]["Product"]["ProductId"]["symbol"] = "SLVO";
$order_preview_para["PreviewOrderRequest"]["Order"]["Instrument"]["orderAction"] = "BUY";
$order_preview_para["PreviewOrderRequest"]["Order"]["Instrument"]["quantityType"] = "QUANTITY";
$order_preview_para["PreviewOrderRequest"]["Order"]["Instrument"]["quantity"] = "1000";

//print_r($order_preview_para);
//echo json_encode($order_preview_para);
//exit;

$ord_preview = $ord_obj->PreviewOrder($account_id_key,$order_preview_para);
//print_r($ord_preview);
//exit;

**Comment by kevinrider** [comment]
I think you are missing the accountIdKey with your request.  Before you can preview or place an order, you need to query and store your unique accountIdKey (which is not related to any other previously assigned E*Trade Id and while not stated in the API docs I believe can be changed at anytime without notice).  Here is the code:

$config = new Config(true);
$ac_obj = new Accounts($config);
$ac = $ac_obj->GetAccountList();
$account_id_key = (string) $ac->Accounts->Account->accountIdKey;

It doesn't appear that you have debugging turned on either.  Turn it on by setting debug_mode = 1 in src/Config.php.  This will output a lot more information about the request and response that is helpful when fixing errors of this type.

**Comment by jharby1** [comment]
I'm already doing that before this code. see below. Its already that. see the previous code right after the preview order. by the way, I already have debug mode set to 1 and this is all i get back. 

$ac     = $ac_obj->GetAccountList();
$account_id_key = (string) $ac->Accounts->Account[3]->accountIdKey;

**Comment by kevinrider** [comment]
This code works fine for me:

require_once __DIR__ . '/../vendor/autoload.php';
use phpetrade\Accounts;
use phpetrade\Order;

$ac_obj = new Accounts();
$ac     = $ac_obj->GetAccountList();
$account_id_key = (string) $ac->Accounts->Account->accountIdKey;

$ord_obj = new Order();
$client_order_id = "testIP7tkL97";  
$ask = "6.09";
$order_preview_para["PreviewOrderRequest"]["orderType"] = "EQ";
$order_preview_para["PreviewOrderRequest"]["clientOrderId"] = "$client_order_id";
$order_preview_para["PreviewOrderRequest"]["Order"]["allOrNone"] = "false";
$order_preview_para["PreviewOrderRequest"]["Order"]["priceType"] = "LIMIT";
$order_preview_para["PreviewOrderRequest"]["Order"]["orderTerm"] = "GOOD_FOR_DAY";
$order_preview_para["PreviewOrderRequest"]["Order"]["marketSession"] = "REGULAR";
$order_preview_para["PreviewOrderRequest"]["Order"]["limitPrice"] = $ask-0.01;
$order_preview_para["PreviewOrderRequest"]["Order"]["Instrument"]["Product"]["securityType"] = "EQ";
$order_preview_para["PreviewOrderRequest"]["Order"]["Instrument"]["Product"]["symbol"] = "SLVO";
$order_preview_para["PreviewOrderRequest"]["Order"]["Instrument"]["Product"]["ProductId"]["symbol"] = "SLVO";
$order_preview_para["PreviewOrderRequest"]["Order"]["Instrument"]["orderAction"] = "BUY";
$order_preview_para["PreviewOrderRequest"]["Order"]["Instrument"]["quantityType"] = "QUANTITY";
$order_preview_para["PreviewOrderRequest"]["Order"]["Instrument"]["quantity"] = "1000";

$ord_preview = $ord_obj->PreviewOrder($account_id_key,$order_preview_para);
print_r($ord_preview);

**Comment by jharby1** [comment]
i'm still getting the same error with the above code. I'm confused because I can get quotes, transactions, account info but not preview or place orders. Any other ideas to check on my settings?

**Comment by kevinrider** [comment]
Based on the error message it appears you are set to a production account.  Has E*Trade upgraded your account to production?  It may not be possible to preview/place orders in the sandbox.

Invalid auth, could also mean that your tokens are expired and you need to authenticate again.

**Comment by jharby1** [comment]
I am in production. Etrade gave me production app api keys. the message was Your active PROD API key is:.... I already re-authenticated the token several times and updated composer several times.

**Comment by kevinrider** [comment]
Have you tried changing the quantity to 1, so its a ~$6 order instead of a ~$6000 order?  How about trying the sample script order with AMZN at a couple bucks? 

Its also possible that there is some additional configuration that needs to be done on your account by ETrade to allow API orders.  The fact that you can use everything but the order endpoints, may mean that you need to contact ETrade customer service.

**Comment by jharby1** [comment]
I figured it out. something very stupid. the rand_order_id needed to be 7 characters instead of 16. it was too long. Thank you for your help. Can you make that commit?

**Comment by kevinrider** [comment]
clientOrderId can be up to 20 characters (its in the docs); however it needs to be different from order to order.  You were most likely receiving the error not because of the difference of 7 to 16, but because the clientOrderId was identical to a previously submitted order.

**Comment by kevinrider** [comment]
Glad you got it figured out!
