### ISSUE TITLE
Q: In the option.php example, are both orderedQuantity and quantity needed? And what's their different meanings?

### ISSUE THREAD

**Issue by mw66** [kevinrider/phpetrade#4]
In the option.php example, are both orderedQuantity and quantity needed? And what's their different meanings?

```
<orderAction>BUY_OPEN</orderAction>
                  <orderedQuantity>1</orderedQuantity>
                  <quantity>1</quantity>
```

Thanks.

**Comment by kevinrider** [comment]
They are defined in the ETrade API:
https://apisb.etrade.com/docs/api/order/api-order-v1.html#/definition/orderPlace
I've always set them to the same, you can contact ETrade support to find out when these might be different.

BTW, you will probably find the orderticket.php examples more useful.  It shows how to setup a one, two, three, or four legged option order w/o worrying about the underlying XML order format.
