### ISSUE TITLE
Oauth not able to respond and giving 401 issue

### ISSUE THREAD

**Issue by r2k1984** [kevinrider/phpetrade#5]
All,

I'm trying to authorize my app and having issues in getting the oatuh token from the response server. 

Tried executing php auth.php and getting the below error.

https://api.etrade.com/oauth/request_tokenResponse: <!doctype html><html lang="en"><head><title>HTTP Status 401 – Unauthorized</title><style type="text/css">h1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} h2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} h3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} body {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} b {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} p {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;} a {color:black;} a.name {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 401 – Unauthorized</h1><hr class="line" /><p><b>Type</b> Status Report</p><p><b>Message</b> oauth_problem=consumer_key_rejected</p><p><b>Description</b> The request has not been applied because it lacks valid authentication credentials for the target resource.</p><hr class="line" /><h3></h3></body></html>

Please help on this.

**Comment by kevinrider** [comment]
This looks like a configuration issue.  Do you have api keys issued by E*Trade?  Sandbox or Production?  You need to set the keys and the correct account type in src/Config.php.

Keep in mind that authorization in this package is only completed by the cli auth.php script.  If you are trying to use a call back via browser, have you setup the redirection url with E*Trade support for your account?

**Comment by r2k1984** [comment]
Please find my response.

1. It is for Sandbox and the keys are populated correctly.
2. When I tried to execute php auth.php , oauth is throwing error. 
3. I haven't setup the callback. I will check with support to update the callback and confirm.

**Comment by r2k1984** [comment]
I'm facing the error in calling the php auth.php file . it is saying Oauth 401 permission issue

**Comment by kevinrider** [comment]
Couple things to try:

1.) Do you have the php oauth module installed correctly?  The readme discusses how to verify the oauth module is loaded into your cli php.  Keep in mind that on some systems the php.ini for the cli is different from the web server module php.ini.

2.) If you're certain the keys are copied correctly to Config.php (and oauth is installed correctly), then perhaps contact E*Trade support to verify your account keys were issued correctly (or ask them to issue new ones).  Its possible incorrect keys were setup on your account.

3.) Its possible, but unlikely, that the sandbox authentication process has changed.  I don't use the sandbox, just production, and its working without issue here.
